### ISSUE TITLE
楼主您好,可以留个联系方式吗,重金求教如何运行...运行不起来太难受了

### ISSUE THREAD

**Issue by YangXiangFeng** [cgpeter96/simple-image-retrieval-system#1]
楼主您好,可以留个联系方式吗,重金求教如何运行...运行不起来太难受了

**Comment by cgpeter96** [comment]
网盘的不能用吗？ 我比较忙啊， 你可以说下你存在的问题，给我发邮件吧 peter_chen_jaon@foxmail.com ， 或者写issue里就行。
